In [ ]:
!pip install urdf2mjcf
!urdf2mjcf D:\source\cmirobot\src\cmirobot\envs\assets\so100\so100.urdf

In [12]:
import numpy
import mujoco
import ikpy
from ikpy.chain import Chain
from cmirobot.envs.transforms import rpy2r, r2rpy,r2w

def get_qpos_joint(model,data,joint_name):
      """
      Get the position for a specific joint.
      
      Parameters:
          joint_name (str): Name of the joint.
      
      Returns:
          np.array: The joint position.
      """
      addr = model.joint(joint_name).qposadr[0]
      L = len(model.joint(joint_name).qpos0)
      qpos = data.qpos[addr:addr+L]
      return qpos

model=mujoco.MjModel.from_xml_path("D:\\source\\cmirobot\\src\\cmirobot\\envs\\assets\\so100\\so100.mjcf")
data=mujoco.MjData(model)
mujoco.mj_forward(model,data)
joint_names=[
                    'shoulder_pan',
                    'shoulder_lift',
                    'elbow_flex',
                    'wrist_flex',
                    'wrist_roll',
                    'gripper']
print(numpy.array([get_qpos_joint(model,data,joint_name) for joint_name in joint_names]).squeeze())

print("data.body(jaw).xpos",data.body("jaw").xpos)
print("data.body(jaw).xquat",data.body("jaw").xquat)
print("data.body(jaw).xmat",data.body("jaw").xmat)
print("xpos",data.xpos)
print("qpos",data.qpos)
print(type(data.qpos))
print("data.joint('floating_base').qpos",data.joint('floating_base').qpos )
print("data.joint('shoulder_pan').qpos",data.joint('shoulder_pan').qpos )
chain=Chain.from_urdf_file("D:\\source\\cmirobot\\src\\cmirobot\\envs\\assets\\so100\\so100.urdf")
print("len(chain.links)",len(chain.links))
target_position = [0.00098806 ,-0.17638859,  0.94712578]
r=numpy.array( [[-1.89803847e-05  ,0.00000000e+00 ,-1.00000000e+00] ,
                [-3.34976228e-01 , 9.42226579e-01 , 6.35797766e-06],
                  [ 9.42226579e-01  ,3.34976228e-01, -1.78838229e-05] ])
target_orientation=r2rpy(r)
joint_angles = chain.inverse_kinematics(target_position= target_position,target_orientation=target_orientation)
# joint_angles=numpy.array([0.0,1.0,1.0,-1.0,1.0,1.0,1.0])
print("joint_angles",joint_angles)

data.qpos[6:]=joint_angles
mujoco.mj_forward(model,data)
print("xpos2",data.xpos)
print("target_position",target_position)
print("data.body(jaw).xpos",data.body("jaw").xpos-data.body("base_link").xpos)


[0. 0. 0. 0. 0. 0.]
data.body(jaw).xpos [-1.27801257e-07 -1.76386463e-01  9.47133757e-01]
data.body(jaw).xquat [-0.69681233 -0.12017937  0.69682556  0.12018165]
data.body(jaw).xmat [-1.89803847e-05  0.00000000e+00 -1.00000000e+00 -3.34976228e-01
  9.42226579e-01  6.35797766e-06  9.42226579e-01  3.34976228e-01
 -1.78838229e-05]
xpos [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  8.00000000e-01]
 [ 0.00000000e+00 -4.52000000e-02  8.16500000e-01]
 [ 0.00000000e+00 -7.57993515e-02  9.19000194e-01]
 [ 0.00000000e+00  4.01883457e-02  9.20691054e-01]
 [ 0.00000000e+00 -9.00017969e-02  9.56406271e-01]
 [ 0.00000000e+00 -1.46629614e-01  9.36274200e-01]
 [-1.27801257e-07 -1.76386463e-01  9.47133757e-01]]
qpos [0.  0.  0.8 1.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
<class 'numpy.ndarray'>
data.joint('floating_base').qpos [0.  0.  0.8 1.  0.  0.  0. ]
data.joint('shoulder_pan').qpos [0.]
len(chain.links) 7
joint_angles [ 0.00000000e+00  7.46736636e-03  1.677103